### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by ssantis** [d10genez/tolita-bamboo#12]
Buenas,
Me interesa el proyecto, sin embargo no tengo experiencia en Bambú, como sería para contactarte?

**Comment by d10genez** [comment]
Hola ssantis
He creado este repositorio con el propósito de impulsar el uso del bambú desde el uso de licencias abiertas. La finalidad es acercar a quien necesite este conocimiento. Dime que necesitas específicamente, mi correo: diogenez@gmail.com

**Comment by d10genez** [comment]
Se ha sustentando el requerimiento.
